name: icecream
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/one.png
    - assets/two.png
    - assets/three.png
    - assets/four.png
    - assets/five.png

fonts:
  - family: RobotoSlab
    fonts:
      - asset: fonts/RobotoSlab-Regular.ttf
  
